# Generated by Django 5.2.10 on 2026-02-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EquipmentUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("csv_file", models.FileField(upload_to="uploads/")),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
