# Generated by Django 5.2.10 on 2026-02-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentupload",
            name="total_equipment",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="equipmentupload",
            name="average_flowrate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="equipmentupload",
            name="average_pressure",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="equipmentupload",
            name="average_temperature",
            field=models.FloatField(default=0.0),
        ),
    ]
